version: '3.5'

services:
    php:
        build:
            context: ..
            dockerfile: docker/php/Dockerfile
            args:
                UID: "${DOCKER_UID}"
        env_file: .env.test
        volumes:
            - ..:/var/www/html
        restart: "no"

    mysql:
        image: mysql:5.7
        restart: "no"
        env_file: .env.test
        tmpfs:
            - /var/lib/mysql
        ports:
            - "3310:3306"
